name: copyright_clinic_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # SVG and Image
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  bloc_concurrency: ^0.3.0

  # Dependency Injection
  get_it: ^7.6.7

  # Network
  dio: ^5.4.0
  dio_cache_interceptor: ^4.0.3

  # Database
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Logging
  logger: ^2.5.0

  # Navigation
  go_router: ^13.2.2

  # Localization
  easy_localization: ^3.0.7+1

  # Path Provider
  path_provider: ^2.1.5

  # helping hand
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/translations/
    
  fonts:
    - family: urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
